file_list = {
    'cvs_avg35_inMNI152_lh_pial.mat',...
    'lAcumb_subcort.mat', ...
    'lAmgd_subcort.mat', ...
    'lBrainStem_subcort.mat', ...
    'lCaud_subcort.mat', ...
    'lFourthVent_subcort.mat', ...
    'lGP_subcort.mat', ...
    'lHipp_subcort.mat', ...
    'lInfLatVent_subcort.mat', ...
    'lLatVent_subcort.mat', ...
    'lPut_subcort.mat', ...
    'lThal_subcort.mat', ...
    'lThirdVent_subcort.mat', ...
    'lVentDienceph_subcort.mat', ...
    'cvs_avg35_inMNI152_rh_pial.mat',...
    'rAcumb_subcort.mat', ...
    'rAmgd_subcort.mat', ...
    'rCaud_subcort.mat', ...
    'rGP_subcort.mat', ...
    'rHipp_subcort.mat', ...
    'rInfLatVent_subcort.mat', ...
    'rLatVent_subcort.mat', ...
    'rPut_subcort.mat', ...
    'rThal_subcort.mat', ...
    'rVentDienceph_subcort.mat'
    };


plot_deep_brain_structures(file_list, 'l', 1); hold on;

load('EC137_electrode.mat');
scatter3(elecmatrix(:,1),elecmatrix(:,2),elecmatrix(:,3),50, 'filled','MarkerFaceAlpha',1,'MarkerFaceColor',[1 1 0]);

% plot_deep_brain_structures(file_list, 'r', 1);