% scripts/Brain_plot_test.m
file_list = {
    'data/brain_structures/cvs_avg35_inMNI152_lh_pial.mat',...
    'data/brain_structures/lAcumb_subcort.mat', ...
    'data/brain_structures/lAmgd_subcort.mat', ...
    'data/brain_structures/lBrainStem_subcort.mat', ...
    'data/brain_structures/lCaud_subcort.mat', ...
    'data/brain_structures/lFourthVent_subcort.mat', ...
    'data/brain_structures/lGP_subcort.mat', ...
    'data/brain_structures/lHipp_subcort.mat', ...
    'data/brain_structures/lInfLatVent_subcort.mat', ...
    'data/brain_structures/lLatVent_subcort.mat', ...
    'data/brain_structures/lPut_subcort.mat', ...
    'data/brain_structures/lThal_subcort.mat', ...
    'data/brain_structures/lThirdVent_subcort.mat', ...
    'data/brain_structures/lVentDienceph_subcort.mat', ...
    'data/brain_structures/cvs_avg35_inMNI152_rh_pial.mat',...
    'data/brain_structures/rAcumb_subcort.mat', ...
    'data/brain_structures/rAmgd_subcort.mat', ...
    'data/brain_structures/rCaud_subcort.mat', ...
    'data/brain_structures/rGP_subcort.mat', ...
    'data/brain_structures/rHipp_subcort.mat', ...
    'data/brain_structures/rInfLatVent_subcort.mat', ...
    'data/brain_structures/rLatVent_subcort.mat', ...
    'data/brain_structures/rPut_subcort.mat', ...
    'data/brain_structures/rThal_subcort.mat', ...
    'data/brain_structures/rVentDienceph_subcort.mat'
    };

plot_deep_brain_structures(file_list, 'l', 1); hold on;

% electrode
load('data/electrode.mat');
scatter3(elecmatrix(:,1),elecmatrix(:,2),elecmatrix(:,3),50, 'filled','MarkerFaceAlpha',1,'MarkerFaceColor',[1 1 0]);

% plot_deep_brain_structures(file_list, 'r', 1);
